[auth]
version = "0.49.1"
[auth.redirections]
allowedUrls = ["https://vocal-access-nine.vercel.app"]
clientUrl = "https://vocal-access-nine.vercel.app"
[auth.signUp]
enabled = true
[functions.node]
version = 20
[hasura]
adminSecret = "{{ secrets.HASURA_GRAPHQL_ADMIN_SECRET }}"
version = "v2.36.10-ce"
[postgres.resources.storage]
capacity = 1
[storage]
version = "0.15.0"