[global]
environment = []

[hasura]
version = "v2.33.0-ce"
[ [placeholder]]
[[hasura.jwtSecrets]]
type = "HS256"
key = "{{ secrets.HOST_JWT_SECRET }}"


[functions.node]
version = 20

[auth]
version = "0.32.1"

[auth.session.accessToken]
expiresIn = 3600

[storage]
version = "0.3.5"
